module.exports = {
    OrganizationError: {
        ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
        FIND_ORGANIZATION_MEMBERS_ERROR: 'FIND_ORGANIZATION_MEMBERS_ERROR',
        FIND_USER_ERROR: 'FIND_USER_ERROR'
    }
}
